FROM node:18-bullseye

# Install python3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Install python dependencies if any
COPY requirements.txt ./
RUN pip3 install -r requirements.txt

EXPOSE 3000
CMD ["node", "server.js"]
